Поправлена валидация
frontend-park-mail-ru/2022_2_Base pull request #17
Opened 2022-10-15 17:15 UTC by Liza1040

2022-10-15 21:25 UTC, tUnknownLegend commented on public/src/pages/LoginPage/LoginPage.js
>              const validation = new Val();
'validation' is assigned a value but never used

2022-10-15 21:27 UTC, tUnknownLegend commented on public/src/pages/RegisterPage/RegisterPage.js
> +        if (document.getElementById(event.target.name + 'Error') !== null) {
```suggestion
        if (!document.getElementById(event.target.name + 'Error')) {
```

2022-10-15 21:32 UTC, tUnknownLegend commented on public/src/pages/RegisterPage/RegisterPage.js
> +     validate(data) {
Эта функция у меня в ПР поуниверсальней перписана. Но как-нибудь совместим ¯\_(ツ)_/¯

2022-10-15 21:36 UTC, tUnknownLegend commented on public/src/pages/RegisterPage/RegisterPage.js
> +            case 400:
Стоит подумать о том, чтобы вынести сообщения об ошибке для каждого кода в модуль ErrorMessages. Но это так, закидушка в будущее, может что получше придумаем

2022-10-15 21:38 UTC, tUnknownLegend commented on public/src/pages/RegisterPage/RegisterPage.js
> +     async DeleteErrorMessage(event) {
лучше сделать отдельным методом, мб даже вынести в модуль ErrorMessages в каком-то универсальном формате

2022-10-15 21:40 UTC, tUnknownLegend commented on public/src/pages/LoginPage/LoginPage.js
> +    validate(data) {
это вынесем в модуль ErrorMessages потом

2022-10-15 21:40 UTC, tUnknownLegend commented on public/src/pages/LoginPage/LoginPage.js
> +    async DeleteErrorMessage(event) {
по аналогии с регестрацией

2022-10-15 21:45 UTC, tUnknownLegend commented
В целом замечания скорее по тому, что надо будет сделать в будущем, а не то, что должно быть готово уже сейчас

2022-10-16 10:58 UTC, Liza1040 commented on public/src/pages/RegisterPage/RegisterPage.js
> +     async DeleteErrorMessage(event) {
Вынесла в модуль ErrorMessage

2022-10-16 10:59 UTC, Liza1040 commented on public/src/pages/LoginPage/LoginPage.js
> +    validate(data) {
Эту функцию я бы тут оставила) Ну, думаю, мы это еще обсудим)

2022-10-17 07:55 UTC, DPeshkoff requested changes

2022-10-17 07:55 UTC, DPeshkoff commented on package.json
>      "eslint": "^8.24.0",
Да и линтер тоже дев-депенденси
В зависимостях-зависимостях должен быть минимум, требуемый для работы, который можно ставить на тачке

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/components/templates.js
> +!function(){var n=Handlebars.template,e=Handlebars.templates=Handlebars.templates||{};e["footer.hbs"]=n({compiler:[8,">= 4.3.0"],main:function(n,e,t,o,a){return'<link rel="stylesheet" href="./src/com
Этого файлика быть не должно

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/modules/ErrorMessage.js
> +        if (document.getElementById(nameId + 'Error') !== null) {
Можно без !== null

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/modules/validation.js
> +        if (data === "") {
Можно проверять длину на 0 или просто !!

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.js
> +        form.addEventListener('focusin', async (event) => {errorMessage.deleteErrorMessage(event.target.name);});
А как мы этот обработчик снимем?)

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.js
> +    validate(data) {
Обертка над модулем ок, только создавать инстансы, как мне кажется, лишнее
Лучше сделать глобальные синглтоны под эту роль

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/pages/MainPage/MainPage.js
На сейчас ок, но в будущем надо бы сделать плашечку для юзера, чтобы он видел, что "что-то пошло не так"

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.js
> +            case 400:
Сами сообщения лучше вообще вынести в константы, чтобы потом, например, было легче переводить

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.js
> +                document.getElementById('serverErrorMessage') === null ?
Можно без null

2022-10-17 07:55 UTC, DPeshkoff commented on public/src/pages/templates.js
> +!function(){var n=Handlebars.template,a=Handlebars.templates=Handlebars.templates||{};a["LoginPage.hbs"]=n({compiler:[8,">= 4.3.0"],main:function(n,a,i,t,s){return'<link rel="stylesheet" href="./src/
Этого файлика тоже быть не должно

2022-10-17 07:58 UTC, DPeshkoff commented
А еще - давай пофиксим так, чтобы проходил CI (там в шаблонах беда)

2022-10-21 14:14 UTC, DPeshkoff requested changes

2022-10-21 14:14 UTC, DPeshkoff commented on package.json
>      "eslint": "^8.24.0",
ping

2022-10-21 14:14 UTC, DPeshkoff commented on public/src/modules/validation.js
> +            return {status: false, message: 'Поле обязательно должно быть заполнено'};
Вроде обсуждали, что унести в константы надо?

2022-10-21 14:14 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.js
> +import ErrorMes from '../../modules/ErrorMessage.js';
```suggestion
import ErrorMessage from '../../modules/ErrorMessage.js';
```
так читабельнее)

2022-10-21 14:14 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.js
> +        form.addEventListener('focusin', async (event) => {
анонимные обработчики - плохо

2022-10-21 15:12 UTC, Liza1040 commented on public/src/pages/RegisterPage/RegisterPage.js
> +        form.addEventListener('focusin', async (event) => {
Мы хотели сначала смерджить, а потом удалить его. Удаление в ветке у Влада

2022-10-21 18:03 UTC, DPeshkoff approved these changes

2022-10-22 03:46 UTC, tUnknownLegend approved these changes

2022-10-22 03:46 UTC, tUnknownLegend commented on public/src/pages/RegisterPage/RegisterPage.js
> +            document.getElementById(event.target.name + 'Error').remove();
Два раза искать одно и тоже два раза может быть не лучшая идея

2022-10-22 03:46 UTC, tUnknownLegend commented on public/src/pages/RegisterPage/RegisterPage.js
> +            const [username, email, password, anotherPassword] = Array.from(data);
```suggestion
            const [username, email, password] = data;
```
anotherPassword не используется и не очень понимаю зачем писать лишние буквы Array.from, поясни

2022-10-23 07:48 UTC, thelvv approved these changes

2022-10-23 12:10 UTC, merged