Base 2.6 components refactoring + deletion event listeners
frontend-park-mail-ru/2022_2_Base pull request #18
Opened 2022-10-15 21:20 UTC by tUnknownLegend

2022-10-17 08:07 UTC, DPeshkoff requested changes

2022-10-17 08:07 UTC, DPeshkoff commented on .eslintrc.json
> +    "max-len": ["error", { "code": 115 }],
А почему такая длина? Оптимально так-то 80, 105 верхняя граница нормы с современными мониторами, а 115...

2022-10-17 08:07 UTC, DPeshkoff commented on package.json
> +    "dep": "screen -d -m -S sudo npm start",
dep как-то не очень, давайте получше название
можно что-то типо deploy:build

2022-10-17 08:07 UTC, DPeshkoff commented on package.json
>      "eslint": "^8.24.0",
Можно в dev-dependency

2022-10-17 08:07 UTC, DPeshkoff commented on public/img/favicon/site.webmanifest
> -    "background_color":"#ffffff",
А куда?

2022-10-17 08:07 UTC, DPeshkoff commented on public/src/components/BaseComponent.js
> +    }
Можно еще метод, который будет вызываться при выходе со страницы

2022-10-17 08:07 UTC, DPeshkoff commented on public/src/components/Header/Header.js
> +            console.log('element not found', headerProfile);
Можно без else

2022-10-17 08:07 UTC, DPeshkoff commented on public/src/components/Header/Header.js
> +    stopEventListener() {
```suggestion
    removeEventListeners() {
```

2022-10-17 08:07 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.js
> +            if (valData !== undefined && !valData.status) {
Можно !!

2022-10-17 20:51 UTC, tUnknownLegend commented on public/src/components/Header/Header.js
> +            console.log('element not found', headerProfile);
зачем логировать, когда элемент нашелся? Через return просто переписать?

2022-10-21 14:23 UTC, DPeshkoff requested changes

2022-10-21 14:23 UTC, DPeshkoff commented on package.json
> -  "contributors": ["Liza", "Alex", "Vlad", "Artem"],
за что(

2022-10-21 14:23 UTC, DPeshkoff commented on public/img/favicon/site.webmanifest
> +{"name":"Reazon by Base","short_name":"Reazon","icons":[{"src":"./android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"./android-chrome-512x512.png","sizes":"512x512","type":"ima
давай на разные строчки разнесем

2022-10-21 14:23 UTC, DPeshkoff commented on public/index.html
> -    <link rel="manifest" href="/img/favicon//site.webmanifest">
сюда надо бы его вернуть

2022-10-21 14:51 UTC, DPeshkoff approved these changes

2022-10-21 14:56 UTC, thelvv approved these changes
Достойно.

2022-10-21 15:01 UTC, Liza1040 approved these changes

2022-10-21 15:19 UTC, merged