Base 2.7 service worker
frontend-park-mail-ru/2022_2_Base pull request #19
Opened 2022-10-24 18:24 UTC by Liza1040

2022-10-29 23:01 UTC, DPeshkoff requested changes

2022-10-29 23:01 UTC, DPeshkoff commented on public/src/index.js
> +const registerServiceWorker = async () => {
Не особо понял, зачем ему быть асинхронным

2022-10-29 23:01 UTC, DPeshkoff commented on public/src/index.js
> +window.addEventListener('load', registerServiceWorker);
Для регистрации нам ждать, в принципе, не обязательно

2022-10-29 23:01 UTC, DPeshkoff commented on public/src/index.js
> +                    console.log('Service worker installing');
```suggestion
                    console.info('Service worker installing');
```

А то спам в логи какой-то получается)

Хотя сообщение "installing" я бы вообще выпилил, не особо вижу в нем смысла. Интересен результат же

2022-10-29 23:01 UTC, DPeshkoff commented on public/src/sw.js
> +                    status: 418,
SW внезапно превращается в чайник?)

2022-10-29 23:01 UTC, DPeshkoff commented on public/src/sw.js
> +                const blob = new Blob([JSON.stringify(data, null, 2)], {type: 'application/json'});
Выглядит страшно! А зачем так?

2022-10-29 23:33 UTC, Liza1040 commented on public/src/index.js
> +const registerServiceWorker = async () => {
Поправила)

2022-10-29 23:48 UTC, Liza1040 commented on public/src/sw.js
> +                    status: 418,
Ага)))

2022-10-29 23:59 UTC, Liza1040 commented on public/src/sw.js
> +                const blob = new Blob([JSON.stringify(data, null, 2)], {type: 'application/json'});
Чтобы выводить пользователю сообщение вместо динозаврика.

2022-10-31 11:53 UTC, DPeshkoff commented on public/src/sw.js
> +                    status: 418,
Вообще можно [503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503), но чайник мемнее, можно и оставить

2022-10-31 11:54 UTC, DPeshkoff approved these changes

2022-10-31 18:40 UTC, tUnknownLegend approved these changes

2022-10-31 18:42 UTC, thelvv approved these changes

2022-10-31 20:50 UTC, merged