Base-2.10 webpack router
frontend-park-mail-ru/2022_2_Base pull request #20
Opened 2022-10-27 14:36 UTC by tUnknownLegend

Пока только роутер, про webpack нам на лекции в пятницу расскажут

2022-10-29 22:46 UTC, DPeshkoff requested changes

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/index.js
> +export default router;
Почему index.js экспортирует роутер?

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/modules/Router.js
> +     * Функция отрисовки страницы регистрации
А регистрации ли?

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/modules/Router.js
> +        const page = new PageConstructor(this.#mainElement);
На всякий случай здесь я бы все-таки проверил, кто таков PageConstructor и function ли он, прежде чем вызывать

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/modules/Router.js
> +     * @param {function} view - страница
view это функция?

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/modules/Router.js
> +     * Функция для рендра страницы при переходе по истории браузера.
```suggestion
     * Функция для рендера страницы при переходе по истории браузера.
```

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/modules/Router.js
> +    }
Не вижу смысла выносить это в такие методы. Плюс название смущает - я сначала вообще подумал, что у вас за стейт логина роутер отвечает)

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/modules/Router.js
> +    openPage(path, config) {
а зачем два разных методах?

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/modules/ErrorMessage.js
> +    render404(target) {
А зачем тогда hbs-шаблон?

2022-10-29 22:46 UTC, DPeshkoff commented on public/src/pages/MainPage/MainPage.js
> +
В будущем этого тут быть не должно

2022-10-31 16:59 UTC, tUnknownLegend commented on public/src/modules/Router.js
> +    openPage(path, config) {
один метод отвечает непосредственно за переход, вторая добавляет страницу в историю браузера и является оберткой для первой. Первую вызываем очивидно, когда не надо записывать в историю, например при самом перехде по истории

2022-10-31 17:02 UTC, tUnknownLegend commented on public/src/modules/Router.js
> +    }
это надо будет в action логина вынести, но пока его нет сделал так. Уберу тогда

2022-11-05 10:20 UTC, DPeshkoff requested changes

2022-11-05 10:20 UTC, DPeshkoff commented on babel.config.js
> +};
я бы еще в es6 прогонял

2022-11-05 10:20 UTC, DPeshkoff commented on public/img/favicon/site.webmanifest
> -{
А что случилось с фавиконками?

2022-11-05 10:20 UTC, DPeshkoff commented on public/index.hbs
> +    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
давайте тогда уж нормальный CSP сделаем)

2022-11-05 10:20 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.scss
> +.paint-purple_login {
во всех файлах: я бы прошелся и посмотрел, что можно оптимизировать с помощью scss

2022-11-05 11:49 UTC, tUnknownLegend commented on public/img/favicon/site.webmanifest
> -{
А они же теперь генерятся автоматом через плагин

2022-11-05 15:49 UTC, DPeshkoff approved these changes

2022-11-05 16:22 UTC, thelvv approved these changes

2022-11-05 16:31 UTC, EuphoriaAbsorber approved these changes

2022-11-05 16:52 UTC, merged