Base 2.11 actions dispatcher
frontend-park-mail-ru/2022_2_Base pull request #21
Opened 2022-10-27 21:15 UTC by Liza1040

2022-10-29 23:22 UTC, DPeshkoff requested changes

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/actions/itemCards.js
> +     * @param {any} id
Почему any?

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/actions/profile.js
> +     * @param {Number} number - номер карты
Зачем нам 16 цифр карты интерпретировать как число?

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/actions/profile.js
> +     * @param {number} code - код
А срок истечения и имя на карте? Некоторые банки это требуют

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/actions/profile.js
> +     * Действие: добавить новый адрес.
Самое главное забыли)
Номер квартиры

Возможно, стоит и страну добавить

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/modules/ErrorMessage.js
> +export default errorMessage;
Можно объединить)

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/modules/dispatcher.js
> +     * @param {int} id идентификатор коллбека
Поймал плюсовика!

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/modules/dispatcher.js
> +        }
Почему так?

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/modules/dispatcher.js
> +        }
А что будет, если без проверки удалить?

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/modules/dispatcher.js
> +        this._callbacks.set(this._lastId++, {callback: newCallback, isPending: false});
А для чего isPending?

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/modules/dispatcher.js
> +        }
А что мы здесь делаем?

2022-10-29 23:22 UTC, DPeshkoff commented on public/src/modules/dispatcher.js
> +                }
Мы же теряем коллбек, получается?

2022-10-30 09:34 UTC, Liza1040 commented on public/src/actions/profile.js
> +     * @param {Number} number - номер карты
String?

2022-10-30 09:47 UTC, DPeshkoff commented on public/src/actions/profile.js
> +     * @param {Number} number - номер карты
Можно так, да

2022-10-30 10:04 UTC, Liza1040 commented on public/src/modules/dispatcher.js
> +        }
Потому то диспетчер сейчас осуществляет рассылку, и, чтобы начать новую, нужно дождаться пока предыдущая будет выполнена.

2022-10-30 10:16 UTC, Liza1040 commented on public/src/modules/dispatcher.js
> +        }
delete вернет false

2022-10-30 10:21 UTC, Liza1040 commented on public/src/modules/dispatcher.js
> +        this._callbacks.set(this._lastId++, {callback: newCallback, isPending: false});
Для отслеживания статуса колбека: вызван ли он.

2022-10-30 10:29 UTC, Liza1040 commented on public/src/modules/dispatcher.js
> +        }
Мы начинаем новую рассылку, и, чтобы диспетчер разослал полезную нагрузку всем обработчикам, нужно привести их в "нулевое" состояние

2022-10-30 10:40 UTC, Liza1040 commented on public/src/modules/dispatcher.js
> +                }
Если isPending = true, то мы же уже вызвали этот колбек.

2022-10-31 09:55 UTC, DPeshkoff requested changes

2022-10-31 09:55 UTC, DPeshkoff commented on public/src/actions/profile.js
> +    saveEditCard(id, number, date, code) {
Здесь не обновлено

2022-10-31 21:22 UTC, DPeshkoff approved these changes

2022-10-31 21:24 UTC, DPeshkoff approved these changes

2022-10-31 21:41 UTC, tUnknownLegend approved these changes

2022-10-31 21:44 UTC, thelvv approved these changes

2022-10-31 22:07 UTC, merged