Base 2.9 base view & store
frontend-park-mail-ru/2022_2_Base pull request #22
Opened 2022-10-31 18:41 UTC by thelvv

2022-10-31 21:48 UTC, tUnknownLegend requested changes

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/views/BaseView.js
> +        // this._isActive = false;
это можно раскомментить

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/views/BaseView.js
> +        // this.addComponent(['HeaderComponent', new HeaderComponent(context)]);
а это наверное не нужно - можно удалить. В любом случае закомментированного кода быть не должно в МР

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        const cardCount = 1; // изначально 0
как ты будешь менять const?

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        const PopUp = document.querySelector('.change-user-photo');
давай будем искать по id, а не по классу. querySelector - не круто

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +            paymentCard.id = `paymentCard${String(1)}`;
почему бы это не сделать сразу при инициализации paymentCard ?

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/components/PaymentCard/paymentCard.hbs
> +            <img class="add-card-pic" src="img/Add_card.svg" alt="PLUS">
```suggestion
            <img class="add-card-pic" src="img/Add_card.svg" alt="add new card">
```

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +            this.paymentCard.render(paymentCard);
я бы вообще не делал const paymentCard, а сразу здесь структуру конструировал и передавал

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        const paymentCard = {
аналогично

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        console.log(this.paymentCard.id);
не забудь убрать

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +    async loadAddressCards() {
аналогично с async loadPaymentCards()

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        // PopUp.style.display = 'none';
комментариев не должно быть

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +    async listenMouseOutAddressCard() {
вместо того, чтобы плодить одинаковые функции нужно сделать две и в них прокидывать имена классов и т.д. через .bind. А лучше перейти от querySelector к getById и передавать ID :)

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        if (Profile) {
опять же нужна обёрточная функция, чтобы не копипастить

2022-10-31 21:48 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        if (Profile) {
аналогично

2022-10-31 22:21 UTC, DPeshkoff commented on public/src/stores/BaseStore.js
> +        if (Dispatcher.isDispatching) {
Это метод, нужно вызывать или обращаться к полю _isDispatching

2022-11-03 12:51 UTC, tUnknownLegend commented on public/src/stores/BaseStore.js
> +        if (Dispatcher.isDispatching) {
исправил [https://github.com/frontend-park-mail-ru/2022_2_Base/pull/23](здесь)

2022-11-03 12:53 UTC, tUnknownLegend commented on public/src/pages/UserPage/UserPage.js
> +        if (Profile) {
ладно, сделаем это позже

2022-11-18 08:53 UTC, closed without merging