Base РК 2
frontend-park-mail-ru/2022_2_Base pull request #26
Opened 2022-11-18 08:54 UTC by tUnknownLegend

2022-11-21 20:30 UTC, DPeshkoff requested changes

2022-11-21 20:30 UTC, DPeshkoff commented on .gitignore
> +#public/index.hbs
кто такой?

2022-11-21 20:30 UTC, DPeshkoff commented on public/index.hbs
> +<!--          content="default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' img.mvideo.ru; style-src 'self' 'unsafe-inline';base-uri 'self'; form-action 'self'; font-src 'self' f
Давайте починим, а не будем выпиливать

2022-11-21 20:30 UTC, DPeshkoff commented on public/index.scss
> +input[type=number] {
что за стили на элементы?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/actions/cart.js
> +            actionName: CartActionTypes.MAKEORDER,
```suggestion
            actionName: CartActionTypes.MAKE_ORDER,
```

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/actions/cart.js
> +import Dispatcher from '../modules/dispatcher.js';
.js?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/actions/itemCards.js
> +import Dispatcher from '../modules/dispatcher';
а тут без .js...

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/actions/profile.js
> +    saveEditData( data) {
что за пробел

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +        const cardID = event.target.id.replace('edit-img-', '');
а не проще в дата-атрибут положить? 

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +    async listenClickEditeAddress(event) {
почему async?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +    async listenClickAddAddress(event) {
почему async?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +    async listenClickEditeAddress(event) {
```suggestion
    async listenClickEditAddress(event) {
```

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +            console.log('element not found', deleteAddress);
можно без лога

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +            console.log('element not found', editAddress);
можно без лога

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +            console.log('element not found', newAddress);
можно без лога

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +                console.log('element not found', newAddress);
можно без лога

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +            console.log('element not found', editAddress);
можно без лога

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.scss
> +//}
кто такой?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/AddressCard.js
> +     * @param {context} context, с учетом которого будет произведен рендер
Не знаю такого типа данных, как context

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/AddressCard/addressCard.hbs
> +                <div class="address-card-city text-normal-default"> д. {{this.house}}, {{#if this.falt}}кв. {{this.flat}}{{/if}}</div>
falt или flat?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CartItem/CartItem.hbs
> +                    <img src="/img/Bin.svg" alt="delete picture" class="button-delete_cart__img">
неправильный alt

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CartItem/CartItem.hbs
> +                <span class="link__no-color" id="button-minus_cart/{{this.id}}">−</span>
страшные айдишники
почему не стали делать дата-атрибуты?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CartItem/CartItem.js
> +    }
в базовом компоненте тот же самый код, в чем смысл?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CartItem/CartItem.scss
> +}
зачем?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CatalogItemCard/CatalogItemCard.hbs
> +                     data-href="/item/{{id}}">
this.id или id?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CatalogItemCard/CatalogItemCard.hbs
> +                <img src="{{this.imgsrc}}" class="catalog-item-card__pic-block__pic" alt="item_photo"
alt некорректный

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CatalogItemCard/CatalogItemCard.hbs
> +                         alt="star_icon">
alt

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CatalogItemCard/CatalogItemCard.hbs
> +                    {{/if}}
что за прибитые молотком propertyName1,2,3,4? не хотите сделать полноценную шаблонизацию?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CatalogItemCard/CatalogItemCard.hbs
> +                    <!--                        {{#if this.favourite}} checked {{/if}}>-->
не понял, куда выпилили

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/CatalogItemCard/CatalogItemCard.js
> +    }
странное переопределение базового класса, если честно
вам принципиально нужен catalogCardItem?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Footer/footer.hbs
>              </div>
можно разбить на подкомпоненты

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Footer/footer.hbs
> +                                                           alt="GitHubLogo"></a>
альт тоже не отражает сути)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Form/form.scss
> +    margin-top: 10px;
опять что-то с кратностью отступов
в файлах выше, кстати, тоже, прошерстите весь код плиз

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Header/Header.js
> +        },
а почему не с бэка? 

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Footer/footer.scss
> +.logo-img {
у вас разве не logo-reazon?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Header/header.scss
> +  margin-left: 20px;
го stylelint

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Header/header.scss
> +.dropdown-content a {
поймал на элементы
откуда брали?)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/Header/header.scss
> +  z-index: 999999;
жесть

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/ItemCard/itemCard.hbs
> +                <span class="link__no-color text-normal-large" ind="itemcard_button-minus_cart/{{this.id}}">−</span>
ind?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/PaymentCard.js
> +        profileAction.deleteCard(Number(event.target.id.replace('delete-img-paymentCard/', '')));
опять что-то страшное
см выше

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/PaymentCard.js
> +            console.log('element not found', paymentCard);
лишнее

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/PaymentCard.js
> +                console.log('element not found', newPaymentCard);
лишнее

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/PaymentCard.js
> +            console.log('element not found', newPaymentCard);
лишнее

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/PaymentCard.scss
> +    //display:grid;
Почему закомментировано? 

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/PaymentCard.scss
> +.card-title-main {
названия классов в этом файле не соответствуют БЭМу, перепишите, пожалуйста

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/PaymentCard.scss
> +    margin-top: -4px;
похоже на костыль

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PaymentCard/paymentCard.hbs
> +                    <img id="delete-img-{{this.id}}" src="/img/deleteButton.svg" class="pop-up-button-pic_user-page delete-payment-card" alt="delete button">
кого удаляем-то? из alt не ясно

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.hbs
> +<form method="post" class="popup-form_add-address" novalidate>
тут тоже классы не по БЭМу

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.js
> +            PopUpFade.style.display = 'none';
может ввести класс и его накидывать и снимать? а то везде инлайн-стили фиксите, прям много где

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.js
> +        const cancel = document.getElementById('popup-form_add-address__cancel');
нет проверки на элемент

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.js
> +        const apply = document.getElementById('popup-form_add-address__apply');
нет проверки на элемент

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.js
> +        apply.removeEventListener('click', this.listenClickApplyBind);
нет проверок на элементы

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.scss
> +.popup-form_add-address__input {
тоже не по БЭМу

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.scss
> +    /* padding: 8px 24px 10px; */
?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddAddress/PopUpAddAddress.scss
> +.popup-form_add-address__cancel {
для чего этот класс нужен? 

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddPaymentCard/PopUpAddPaymentCard.js
> +        apply.removeEventListener('click', this.listenClickApply);
тоже проверок не завезли

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddPaymentCard/PopUpAddPaymentCard.scss
> +.popup-form_add-card__header {
и тут не БЭМ

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddPaymentCard/PopUpAddPaymentCard.scss
> +    padding: 10px 14px 11px;
некратное

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpAddPaymentCard/PopUpAddPaymentCard.scss
> +.popup-form_add-card__cancel {
опять он! я его уже видел

1) переиспользуйте код, не надо копипастить
2) в чем смысл этого класса

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpChooseAddressAndPaymentCard/PopUpChooseAddressAndPaymentCard.js
> +            chooseAddress.style.border = '1px solid #6369D1';
вот такое точно я бы не стал инлайнить

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpChooseAddressAndPaymentCard/PopUpChooseAddressAndPaymentCard.js
> +                key.addEventListener('click', this.listenClickAddressAndPaymentCard.bind(null, fieldId));
я бы не стал байндить тут - лучше сделать это в другом месте, переопределив this.listenClickAddressAndPaymentCard и только затем его вешать как обработчик

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpChooseAddressAndPaymentCard/PopUpChooseAddressAndPaymentCard.scss
> +    /* padding: 8px 24px 10px; */
чую очередную копипасту
может это вынести в какой-нибудь PopUpCommon.scss?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpEditUserInfo/PopUpEditUserInfo.hbs
> +                <input maxlength="41" class="popup-form_user-info__input text-normal-default" name="{{this.name}}" id="{{this.id}}"
специфично. почему 41?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpEditUserInfo/PopUpEditUserInfo.js
> +                    id: context.id + '__popUp',
кажется, в таких местах было бы нагляднее через обратные кавычки
но это уже вкусовщина

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpEditUserInfo/PopUpEditUserInfo.js
> +        switch (context.id) {
вообще прикольный конструктор получился
непонятно, почему не шаблонизатором, а js сделали
в чем была идея именно такой реализации?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpEditUserInfo/PopUpEditUserInfo.js
> +        apply.addEventListener('click', this.listenClickApplyBind);
ну тут сами поймете, что не так)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/components/PopUpEditUserInfo/PopUpEditUserInfo.scss
> +}
в этом файле все замечания - аналогичны

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/config.js
> +    // basePath: 'http://127.0.0.1:8080',
?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/config.js
> +        login: basePathApi + 'login',
вот здесь точно бы строки с обратными кавычками запилил

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/index.js
>      }
почему здесь логика роутера лежит?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/index.js
> +        refresh.onLogOut();
тоже не понял, что это здесь такое
можно же экшон разлогина бросать

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/ErrorMessage.js
> +     * @param {object} target - HTML-элемент, после (до) которого будет осуществлена отрисовка
object?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/ErrorMessage.js
> +                        </div>`);
а почему не шаблон?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/ErrorMessage.js
> +                if (!(exError.innerText === valData.message)) {
можно объединить условия

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/Router.js
> +        // this.register(config.href.user, UserPage); //fix
так чего там насчет фикса?)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/Router.js
> +        goToPath = goToPath ? goToPath : path;
а в чем смысл? можно константу в одной строчке определять с проверкой...

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/ajax.js
> +        // 'Origin': 'http://localhost:8081',
в итоге у вас нет никакого ориджина
зачем безопасность убили? к требованиям каждого рк написано "не сломать предыдущие рк"

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/ajax.js
> +    makePostRequestSendAva = async (url, data) => {
ava = )

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/refreshElements.js
> +     * @param {boolean} auth - контекст отрисовки компонента
неправда, это не контекст, это auth

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/modules/sharedFunctions.js
> +class SharedFunctions {
самый главный вопрос

а почему это класс? эти функции ничего между собой не объединяет

если уж хочется сделать модуль с sharedFunctions - экспортируйте все эти функции и просто импортируйте нужные

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +        cartStore.addListener(this.getCart.bind(this), CartActionTypes.GET_CART);
bind лучше отдельно делать

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +        deleteElement.remove();
каждый свой день я начинаю с попытки remove'ать undefined)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +                sumVal[0] += key.lowprice * key.count ?? key.price * key.count;
ничего не понятно
но интересно

к таким сложным элементам нужно бы побольше комментариев - что конкретно здесь мы редьюсим и зачем это сделано именно так (а не через объект с 4 полями)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +            context.isAuth = true; // FIX
ISWYDT

давайте пофиксим

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +            <div class="paint-background"></div>`;
Почему не шаблон?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +            break;
а где загрузка-то? не очень понятно

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +    async listenClickAddressAndPaymentCardBlock(event) {
switch внутри switch это красиво, но давайте это декомпозируем

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +                    if (isNaN(price)) {
а почему не number.isNaN? в чем разница?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +        discount.textContent = summary.priceDiff + ' ₽';
выглядит, как задача для шаблонизатора

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +                0)).toJSON();
что здесь происходит? почему так сложно, нет пояснений и не вынесено в utils какой-нибудь?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +            const currDate = new Date(new Date().getTime() + next * 24 * 60 * 60 * 1000);
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +            return `${currDate.getDate()} / ${currDate.getMonth()} / ${currDate.getFullYear()}`;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.scss
> +  height: 3ex;
почему решили взять ex?)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.scss
> +
поясните, плиз, что происходит))

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.scss
> +.option_select:hover {
не по БЭМу, кстати

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.scss
> +  left: -40000px;
ну ничего себе

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.scss
> +.select:focus .select-opt:checked + .option_select {
сложные селекторы - зло, лишнее время на обработку css

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.hbs
> +        </div>
для чего этот див?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.js
> +    lisitenSortCatalog(event) {
опечатка

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.js
> +     *  @param {HTMLElement} event - событие, вызвавшее клик.
событие это не HTMLElement

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.js
> +        if ((scrollY + innerHeight > (0.8 * document.body.scrollHeight))) {
магия вне Хогвартса требует пояснений в лице комментариев

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.js
> +            if (!this.waitThrottleScroll) {
а спиннер загрузки есть? 

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.scss
> +.catalog_filter-block__body {
не БЭМ

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.hbs
> +        <img type="image" class="login-right-img" src="/img/LoginRightImg.webp" alt="LoginRightImg">
alt не верный

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.js
>  const ERROR_401_MESSAGE = 'Неверная почта или пароль';
в файлик с константами

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.js
> +                console.log('server error: ', status);
у вас есть всплывашка ошибок, давайте сюда ее встроим

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/MainPage/MainPage.js
> +        if (event.target.getAttribute('ind')) {
можно же было сделать дата-атрибут

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/MainPage/MainPage.js
> +                itemCount.forEach((item) => item.textContent = '1');
выглядит очень костыльно

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.hbs
> +        <img type="image" class="LoginRightImg" src="/img/LoginRightImg.webp" alt="LoginRightImg">
alt

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.js
>  const ERROR_401_MESSAGE = 'Неверная почта или пароль';
в константы, дублирование кода

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.js
> +            router.openPage(config.href.main); // fix change to prev
что за фикс?)

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.hbs
> +                       accept="image/jpeg, image/png, image/jpg">
а webp?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.hbs
> +                    <img class="edit-button_user-page" src="/img/editButton.svg" alt="edit button">
alt - кого эдитим?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.hbs
> +                         alt="delete button">
alt - кого эдитим и делитим?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.js
> +        userStore.addListener(this.templateFunction.bind(this, this.renderAddresses.bind(this)),
bind внутри bind... не очень читабельно

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.js
> +    templateFunction(toDo) {
а проверить, точно ли это функция?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.js
> +            console.log('element not found', this.paymentCard);
лишнее

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.js
> +            console.log('element not found', this.addressCard);
лишнее

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.js
> +    startEventListener() {
console log лишние

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.scss
> +.payment-cards-items_user-page {
не БЭМ

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.scss
> +  //align-self: end;
остался мусор

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.scss
> +  margin-top: -90px;
чем обусловлена такая радость? 

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.scss
> +  //align-self: center;
что-то лишнее

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/pages/UserPage/UserPage.scss
> +  right: 0;
https://developer.mozilla.org/en-US/docs/Web/CSS/inset

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +    };
на фронте такого быть не должно

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +        console.log('response', response);
дебаг-логи

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +        if (status === config.responseCodes.code200) {
а если не 200?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +            if (postStatus === config.responseCodes.code200) {
а если не 200?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +        if (status === config.responseCodes.code200) {
а если не 200?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +            .catch((err) => console.log(err));
так-то у вас оно здесь должно обработаться, но зачем так странно статусы обрабатывать?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +        });
filter? find?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +     * @param {int} id
что за инты

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +    }
ну вот так и знал, что дублирование будет)
выносите в utils

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/ItemsStore.js
> +    };
этих товарищей тут быть тоже не должно, по-хорошему...

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/ItemsStore.js
> +    }
пустое(

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/ItemsStore.js
> +                cartItems.forEach((cartItem) => {
o(n^2) или сколько тут?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/ItemsStore.js
> +        this._storage.set(this._storeNames.responseCode, status);
нечитабельно совсем
вынесите это куда-нибудь, пожалуйста, в переменные или методы

2022-11-21 20:30 UTC, DPeshkoff commented on server/index.js
> +// });
а зачем убили?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> + * Класс, реализующий базовое хранилище.
опечатка в названии файла

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> +    ];
что за тестовые данные?

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> +                isValid &= errorMessage.validateField(validation.validatePhone(value),
чем обусловлен такой оператор? выглядит так, будто у вас что-то не то с архитектурой

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> +    #validateCard(data) {
кажется, валидация обитает в modules/validation

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> +    #validateAddress(data) {
аналогично

2022-11-21 20:30 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> +     * @param {int} id - идентификатор элемента
int

2022-11-21 20:32 UTC, DPeshkoff requested changes
Посмотрел код

2022-11-21 20:53 UTC, tUnknownLegend commented on public/src/components/Header/Header.js
> +        },
Категории не меняются - нетт смысла зря делать запрос

2022-11-21 20:56 UTC, tUnknownLegend commented on public/src/components/PopUpEditUserInfo/PopUpEditUserInfo.hbs
> +                <input maxlength="41" class="popup-form_user-info__input text-normal-default" name="{{this.name}}" id="{{this.id}}"
В инпут форме так красивее всего было

2022-11-21 21:00 UTC, tUnknownLegend commented on public/src/modules/Router.js
> +        // this.register(config.href.user, UserPage); //fix
это просто надо убрать, но для тестов нужно, чтобы можно было на локалке в профиль перейти

2022-11-21 21:03 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +            context.isAuth = true; // FIX
тут все норм - опять же чисто для тестов на локалке

2022-11-21 21:05 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +                0)).toJSON();
Этом мы из двух полей ввода на фортне парсим время и дату и делаем из них Date

2022-11-21 21:07 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.scss
> +  left: -40000px;
то чего пользовтель не видит - того и нет ;)

2022-11-21 21:08 UTC, tUnknownLegend commented on public/src/pages/CatalogPage/CatalogPage.js
> +        if ((scrollY + innerHeight > (0.8 * document.body.scrollHeight))) {
смотрим, если положение скролла меньше чем 0.8 длинны страницы

2022-11-21 21:09 UTC, tUnknownLegend commented on public/src/pages/CatalogPage/CatalogPage.js
> +            if (!this.waitThrottleScroll) {
не очень понял что есть спинер

2022-11-21 21:10 UTC, tUnknownLegend commented on public/src/pages/RegisterPage/RegisterPage.js
> +            router.openPage(config.href.main); // fix change to prev
чтобы на прошлую страницу переходило в истории - никак руки не доходят

2022-11-21 21:12 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +    };
это моки для отладки, они не используются на проде

2022-11-21 21:13 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +        if (status === config.responseCodes.code200) {
если не 200 - ничего менять не будем, просто сообщение об ошибке (надеюсь) покажем

2022-11-21 21:15 UTC, tUnknownLegend commented on public/src/stores/UserStrore.js
> +    ];
опять же для отладки

2022-11-21 21:19 UTC, tUnknownLegend commented on public/src/components/Header/Header.js
> +        },
либо здесь либо в сторе можно удалить, мб лучше в сторе, потому что только здесь это нужно

2022-11-21 21:34 UTC, tUnknownLegend commented on public/src/index.js
> +        refresh.onLogOut();
так он слушает этот экшон и отрегивает страницы роутера

2022-11-21 21:34 UTC, tUnknownLegend commented on public/src/modules/ajax.js
> +        // 'Origin': 'http://localhost:8081',
да, надо раскомментить

2022-11-21 21:37 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +            <div class="paint-background"></div>`;
Не хотелось уже в шаблон лезть, проще было так сделать, да и в целом, если успеем надо бы на jsx перейти...

2022-11-21 21:38 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +            break;
Там они сразу подставляются без ответа сервера, а если сервер 500 кинул, то показываем ошибку

2022-11-21 21:39 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +    async listenClickAddressAndPaymentCardBlock(event) {
Надо сделать базовый попап и от него наследоваться, пока этого нет проблемы и css и с этим... Но мы сделаем :)

2022-11-21 21:48 UTC, tUnknownLegend commented on public/src/components/Header/header.scss
> +  margin-left: 20px;
настроил, только в другой ветке уже, мб сюда и не вмержим уже, но скорее вмержим

2022-11-22 08:03 UTC, DPeshkoff commented on public/src/index.js
> +        refresh.onLogOut();
а почему он это делает вне диспетчера? не лучше ли сделать сущность обновлятора, которая будет подписана на стор и действовать в той же системе координат?

2022-11-22 08:04 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +            context.isAuth = true; // FIX
на проде не раскомменчено, где же норм-то

2022-11-22 08:04 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +            break;
довольно неочевидная система, если честно

2022-11-22 08:04 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +    async listenClickAddressAndPaymentCardBlock(event) {
а когда?)

2022-11-22 08:05 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.js
> +        if ((scrollY + innerHeight > (0.8 * document.body.scrollHeight))) {
я к тому, что в таких местах нужны дополнительные комментарии в коде)

2022-11-22 08:06 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.js
> +            router.openPage(config.href.main); // fix change to prev
довольно критично - давайте чинить

2022-11-22 08:07 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +    };
ну и давайте выпилим тогда

2022-11-22 08:07 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +        if (status === config.responseCodes.code200) {
давайте прямо ситуацию обработаем)

2022-11-22 08:07 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> +    ];
выпиливаем)

2022-11-23 23:45 UTC, thelvv commented on public/src/components/Footer/footer.scss
> +.logo-img {
Это для лого ВК, TG и гитхаба около имен членов команды

2022-11-23 23:48 UTC, thelvv commented on public/src/components/Header/header.scss
> +.dropdown-content a {
Из примеров dropdown'ов

2022-11-24 00:46 UTC, thelvv commented on public/src/pages/CartPage/CartPage.scss
> +
Кастомизация чекбоксов

2022-11-24 00:50 UTC, thelvv commented on public/src/pages/CatalogPage/CatalogPage.hbs
> +        </div>
Чтобы оставить текущую ячейку грида пустой

2022-11-26 13:53 UTC, tUnknownLegend commented on public/src/components/CartItem/CartItem.hbs
> +                <span class="link__no-color" id="button-minus_cart/{{this.id}}">−</span>
Мы попробовли сделать через id, чтобы не использовать querySelector, решение оказалось спорным, но рабочим

2022-11-26 15:16 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +        if (status === config.responseCodes.code200) {
ошибка же во view отображается, поэтому написал надеюсь, а так 100% что обрабоатем)

2022-11-26 15:19 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +            .catch((err) => console.log(err));
Ты про `.catch((err) => console.log(err))`? Или про `status`? статусы все кладутся в мапку `this._storage.set(this._storeNames.responseCode, status);` и потом во вьюшке чекаются. `catch` тут на всякий, так как промис возвращяется.

2022-11-26 15:28 UTC, tUnknownLegend commented on public/src/stores/UserStrore.js
> + * Класс, реализующий базовое хранилище.
что-то не вижу опечатки, вроде корзина, все верно

2022-11-26 15:53 UTC, tUnknownLegend commented on public/src/components/CartItem/CartItem.hbs
> +                <span class="link__no-color" id="button-minus_cart/{{this.id}}">−</span>
Надо бы переделать, но когда -_-

2022-11-26 17:45 UTC, tUnknownLegend commented on public/src/modules/Router.js
> +        goToPath = goToPath ? goToPath : path;
сдеал одной строчкой, но не уверен что так лучше, ?? не получается тут заюзать, так как пустая стринга возвращается :(

2022-11-26 18:18 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +    async listenClickAddressAndPaymentCardBlock(event) {
не знаю, пока не успеваю :\ Вынес второй свитч, чтобы не так страшно выглядело

2022-11-26 18:25 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +                    if (isNaN(price)) {
`isNaN` еще проверяет может ли переменная быть конвертирована в число. Посклоьку у нас точно должно быть число, то корректнее твой вариант

2022-11-26 18:33 UTC, tUnknownLegend commented on public/src/pages/CatalogPage/CatalogPage.js
> +            if (!this.waitThrottleScroll) {
Теперь понял, нет

2022-11-26 18:46 UTC, tUnknownLegend commented on public/src/stores/ItemsStore.js
> +                cartItems.forEach((cartItem) => {
получается что так, но пока в голову не приходит как переписать :\

2022-11-26 20:22 UTC, tUnknownLegend commented on public/src/components/Header/header.scss
> +.dropdown-content a {
мы попозже уберем завязку не элементы, в одном из следующих МРов он по-другому сделан в целом

2022-11-26 21:00 UTC, DPeshkoff requested changes

2022-11-26 21:00 UTC, DPeshkoff commented on public/index.scss
> +input[type="number"] {
приколы какие-то(

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/components/InfoCard/AddressCard/AddressCard.scss
> +//.address-card:hover {
кто такое

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/components/ItemCard/itemCard.hbs
> +                <span class="link__no-color text-normal-large" ind="itemcard_button-minus_cart/{{this.id}}">−</span>
так что за ind?

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/components/popUp/PopUpAddAddress/PopUpAddAddress.scss
> +    /* padding: 8px 24px 10px; */
кто

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/components/popUp/PopUpAddPaymentCard/PopUpAddPaymentCard.scss
> +    /* padding: 8px 24px 10px; */
кто

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/components/popUp/PopUpEditUserInfo/PopUpEditUserInfo.js
> +import {config} from '../../../config';
почините ворнинг

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/components/popUp/PopUpEditUserInfo/PopUpEditUserInfo.scss
> +    /* padding: 8px 24px 10px; */
кто

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/modules/Router.js
> +import UserPage from '../pages/UserPage/UserPage';
почините ворнинг

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CatalogPage.hbs
> +        </div>
костыльно

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/stores/UserStrore.js
> + * Класс, реализующий базовое хранилище.
userst_r_ore

2022-11-26 21:00 UTC, DPeshkoff commented on public/src/stores/CartStore.js
> +import {getDate} from '../modules/sharedFunctions';
поправьте ворнинг (такой лучше бы в ошибки выносить сразу)

2022-11-26 21:00 UTC, DPeshkoff commented on webpack.config.js
> +            // files: './public/*',
комментики

2022-11-26 22:26 UTC, DPeshkoff requested changes

2022-11-26 22:26 UTC, DPeshkoff commented on public/index.hbs
> +<!--          content="default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' img.mvideo.ru; style-src 'self' 'unsafe-inline';base-uri 'self'; form-action 'self'; font-src 'self' f
а чего оно вернулось?

2022-11-26 22:35 UTC, DPeshkoff approved these changes
Мне ок!

2022-11-26 22:36 UTC, merged