Base 2.22 typescript
frontend-park-mail-ru/2022_2_Base pull request #34
Opened 2022-12-08 22:30 UTC by tUnknownLegend

2022-12-10 20:05 UTC, DPeshkoff requested changes

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/components/BaseComponent.ts
> +    removeEventListener() {}
https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/components/BaseComponent.ts
> +    render(context: unknown,
а почему unknown?

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/components/Header/Header.ts
> +        const category = this.#isSearchContainsCategory() as topCategoryElement; // fix
?

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/components/InfoCard/BaseInfoCard.ts
> +    async listenClickAdd(event: Event) {
_event, если не используется, чтобы не ругалось)

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/components/popUp/PopUpEditUserInfo/PopUpEditUserInfo.ts
> +            // data.fields.field2.id = context.id + '__2__popUp';
куда?

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/modules/sharedFunctions.ts
> +        // item.price = null;
?

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/modules/validation.ts
> +    validatePhone(phone: string) {
возвращаемому результату тоже можно тип указывать

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/pages/ItemPage/AddCommentPage/AddCommentPage.ts
> +     * Функция, регистрирующая листенеры сторож
сторож

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/pages/LoginPage/LoginPage.ts
> +        // }
?

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/pages/MainPage/MainPage.ts
> +            addToCartButton.forEach((button) => (button as any).style.display = 'none');
а почему as any, а не as HTMLElement?

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/pages/MainPage/MainPage.ts
> +                    addToCartButton.forEach((button) => (button as any).style.display = 'flex');
аналогично

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/pages/RegisterPage/RegisterPage.ts
> +        // }
?

2022-12-10 20:05 UTC, DPeshkoff commented on public/src/stores/ItemsStore.ts
>              await this._getItemCard(payload.data);
давайте починим

2022-12-10 20:25 UTC, tUnknownLegend commented on public/src/components/BaseComponent.ts
> +    render(context: unknown,
unknown - сейвовая версия any. Если у переменный тип unknown, мы не можем выполнять никаких специфических действий, пока не скастим к какому-то определенному типу

2022-12-10 22:13 UTC, tUnknownLegend commented on public/src/components/BaseComponent.ts
> +    removeEventListener() {}
этот метод должен быть пустым в некоторых классах. Проще сделать его пустым один раз

2022-12-10 22:14 UTC, tUnknownLegend commented on public/src/components/InfoCard/BaseInfoCard.ts
> +    async listenClickAdd(event: Event) {
не помогло(

2022-12-10 22:15 UTC, tUnknownLegend commented on public/src/modules/validation.ts
> +    validatePhone(phone: string) {
да, но он же автоматически определяется, не совсем понятно зачем это делать вне экстравагантных ситуаций

2022-12-12 00:57 UTC, DPeshkoff approved these changes

2022-12-12 05:15 UTC, merged