Base 3.1 promocode
frontend-park-mail-ru/2022_2_Base pull request #35
Opened 2022-12-10 10:07 UTC by thelvv

2022-12-10 12:50 UTC, tUnknownLegend requested changes

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +        this._storage.set(this._storeNames.promocodeReqStatus, status);
```suggestion
        this._storage.set(this._storeNames.responseCode, status);
```

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +        this._storage.set(this._storeNames.promocode, data);
особого смысла нет сохранять здесь промокод, потому что он все время с бека будет приходить, а при применении он и так уже на странице

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +                this._storage.set(this._storeNames.promocode, response.promocode);
```suggestion
                this._storage.set(this._storeNames.promocodeIsValid, false);
```

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +            this._storage.set(this._storeNames.promocodeStatus, response.promocodeStatus);
```suggestion
            this._storage.set(this._storeNames.promocodeIsValid, response.promocodeStatus);
```

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +        this._storage.set(this._storeNames.promocode, null);
убираем все кроме промокода, он в get cart пригодится

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/stores/CartStore.js
> +        promocode: 'promocode',
убираем

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.scss
> +  grid-template-rows: 2.6fr 4fr 2fr;
2.6 fr лучше не надо. Подумай как по-другому можно сделать. Возможно min-content поможет

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +        const promocodeStr = document.getElementById('cart-promocode-field').value;
проверить, что элемент нашелся, прежде чем получать value

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +        if (data && data.length) { // || true для локального отображения корзины
не забудь убрать

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +            if (promocodeStatus === 0) {
switch?

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +            if (promocodeStatus === 0) {
=== 0?

2022-12-10 12:50 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +            if (promocodeStatus === 0) {
Должен быть чек кода ответа и truthy статуса самого промика

2022-12-10 22:46 UTC, tUnknownLegend requested changes

2022-12-10 22:46 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +                    promocodeStatusText.textContent = 'Повторите попытку позже';
81 и 85 строки - одинковые сообщения об ошибки

2022-12-10 22:46 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +        if (promocodeStr && promocodeStr.value &&
```suggestion
        if (promocodeStr instanceof HTMLinputelement
```

2022-12-12 01:02 UTC, DPeshkoff requested changes
Давайте тоже сюда подольем ts после мерджа?

2022-12-12 01:02 UTC, DPeshkoff commented on public/src/pages/CartPage/CartPage.js
> +        // context.priceDiff = context.noSalePrice - context.sumPrice;
?

2022-12-12 01:02 UTC, DPeshkoff commented on public/src/config.js
> +        applyPromocode: `${basePathApi}applypromo`, // исправить, когда будет ручка
а когда будет и на что исправить? давайте обсудим апишку

2022-12-12 21:28 UTC, tUnknownLegend commented on public/src/config.js
> +        applyPromocode: `${basePathApi}applypromo`, // исправить, когда будет ручка
как Артем назовет, такое и будет название :)

2022-12-12 21:29 UTC, tUnknownLegend commented on public/src/pages/CartPage/CartPage.js
> +        // context.priceDiff = context.noSalePrice - context.sumPrice;
получается уже не актуально, цена будет на беке меняться при вводе промо

2022-12-15 14:48 UTC, tUnknownLegend requested changes

2022-12-15 14:48 UTC, tUnknownLegend commented on public/src/actions/cart.ts
> +     * @param {String} data - строка с промокодом
в ts тип не пишется в доке

2022-12-15 14:48 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +        router.refresh();
ты перезашружаешь странцу в любом случае. Нам надо перезгружть страницу, только когда промокод применен. Если промокод не применен - показываешь об этом сообщение и не перезагружаешь. Если промокод применен, то вся загрузка просиходит через шаблон и js вообще не нужен

2022-12-15 14:48 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +        router.refresh();
аналогично

2022-12-15 14:50 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +        if (promocodeStr && promocodeStr instanceof HTMLInputElement) {
```suggestion
        if ( promocodeStr instanceof HTMLInputElement) {
```

2022-12-15 14:51 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +            } else if (promocodeStr.value) {
лишнее

2022-12-15 14:52 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +                if (!/^[a-z0-9 а-яА-ЯёЁ!?()_-]+$/i
вынести в validation, там уже есть похожий метод, надо сделать отдельную функцию для таких проверок и ее вызвать везде где нужно

2022-12-15 15:08 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +            if (cartStore.getContext(cartStore._storeNames.responseCode) ===
39 и 40 в один if можно

2022-12-17 11:11 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +     * импортированному из templates.js
templates.js?

2022-12-17 11:19 UTC, tUnknownLegend requested changes

2022-12-17 11:19 UTC, tUnknownLegend commented on public/src/modules/validation.ts
> +        if (!this.validateString(searchString)) {
```suggestion
        if (this.validateString(searchString)) {
```

2022-12-17 11:19 UTC, tUnknownLegend commented on public/src/stores/CartStore.ts
> +            // promocodeStatus = true, когда промокод валидный
не очень понятно к чему это

2022-12-17 11:19 UTC, tUnknownLegend commented on public/src/components/ApplyPromocodeBlock/ApplyPromocodeBlock.ts
> +                router.refresh();
Вопрос остался - зачем делать что-то кроме обновления старинцы в js, если ты все равно этой командой полностью перепендриваешь страницу? Если я правильно понимаю, то сейчас сообщение о статусе промокда будет только после применения, а когда человек второй раз зайдет в корзину будет непонятно что делает промокод

2022-12-19 06:47 UTC, tUnknownLegend approved these changes

2022-12-19 14:59 UTC, DPeshkoff approved these changes

2022-12-19 14:59 UTC, merged