Base 3.2 bugs and improvements rk3
frontend-park-mail-ru/2022_2_Base pull request #37
Opened 2022-12-13 21:02 UTC by tUnknownLegend

2022-12-19 00:21 UTC, DPeshkoff requested changes

2022-12-19 00:21 UTC, DPeshkoff commented on public/src/pages/CatalogPage/CategoryPage/CategoryPage.ts
> +            // this.itemsBlock.innerHTML = '';
куда?

2022-12-19 00:21 UTC, DPeshkoff commented on public/src/pages/CatalogPage/SearchPage/SearchPage.ts
> +            // this.itemsBlock.innerHTML = '';
куда?

2022-12-19 06:56 UTC, tUnknownLegend commented on public/src/pages/CatalogPage/CategoryPage/CategoryPage.ts
> +            // this.itemsBlock.innerHTML = '';
теперь в компоненте все делается, чтобы все плавно рендрило

2022-12-19 14:58 UTC, DPeshkoff approved these changes

2022-12-20 14:51 UTC, thelvv approved these changes

2022-12-20 14:59 UTC, Liza1040 approved these changes

2022-12-20 15:04 UTC, merged